[package]
name = "dummy-contract"
version = "0.0.6"
authors = ["Dummy"]
license = "Apache-2.0"
edition = "2021"
description = "desc"


[dependencies]
soroban-sdk = { version = "20.0.0-rc2" }

[dev_dependencies]
soroban-sdk = { version = "20.0.0-rc2", features = ["testutils"] }
