[package]
name = "soroswap-factory-interface"
authors = ["esteblock <esteblock@paltalabs.io>"]
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
soroban-sdk = { version = "20.0.0" }

[dev_dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] }